name: Deploy React (Vite) to Railway (Production)
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: ${{ vars.PACKAGE_MANAGER }}

      - name: Cache Node.js modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |-
            ~/.npm
            ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles(format('{0}.lock', vars.PACKAGE_MANAGER)) }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: ${{ vars.INSTALL_COMMAND }}

      - name: Build React (Vite) Application
        run: ${{ vars.BUILD_COMMAND }}

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ vars.RAILWAY_PROJECT_ID }}
        run: railway up
